name: test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * MON'
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  prerelease:
    name: Create artifacts and optionally prerelease the package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -e
          sudo apt-get -qy update
          sudo apt-get -qy install --no-install-recommends libfontconfig1 zip
      - name: Install TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            alphalph
            biber
            biblatex
            booktabs
            csquotes
            enumitem
            hologo
            hypdoc
            latex
            latex-bin
            latexmk
            scheme-basic
      - name: Typeset documentation
        run: latexmk lt3luabridge.dtx
      - name: Produce lt3luabridge.zip
        run: |
          set -e
          ln -s . lt3luabridge
          zip -@ lt3luabridge < RELEASE_FILES
      - name: Upload artifact lt3luabridge.zip
        uses: actions/upload-artifact@v2
        with:
          name: lt3luabridge.zip
          path: lt3luabridge.zip
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            lt3luabridge.zip
