name: test & publish
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * MON'
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  markdownlint:
    name: Run MarkdownLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run MarkdownLint
        uses: nosborn/github-action-markdown-cli@v2.0.0
  test:
    name: Compile example document
    needs:
      - markdownlint
    strategy:
      fail-fast: true
      matrix:
        command:
          - texexec  --passon="--shell-escape --8bit --interaction=nonstopmode" example.context
          - context                                              --nonstopmode  example.context
          - pdflatex --shell-escape                  --interaction=nonstopmode  example.latex
          - xelatex  --shell-escape --8bit           --interaction=nonstopmode  example.latex
          - lualatex                                 --interaction=nonstopmode  example.latex
          - pdftex   --shell-escape                  --interaction=nonstopmode  example.plaintex
          - xetex    --shell-escape --8bit           --interaction=nonstopmode  example.plaintex
          - luatex                                   --interaction=nonstopmode  example.plaintex
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest-with-cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends poppler-utils ruby
      - name: Compile example document
        run: ${{ matrix.command }}
      - name: Extract text of the example document
        run: pdftotext example.pdf
      - name: Check the text of the example document
        run: grep '1+2=3' example.txt
