name: test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * MON'
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  markdownlint:
    name: Run MarkdownLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run MarkdownLint
        uses: nosborn/github-action-markdown-cli@v2.0.0
  test:
    name: Compile example document
    strategy:
      fail-fast: true
      matrix:
        command:
          - texexec  --passon="--shell-escape --8bit --interaction=nonstopmode" example.context
          - context                                              --nonstopmode  example.context
          - pdflatex --shell-escape                  --interaction=nonstopmode  example.latex
          - xelatex  --shell-escape --8bit           --interaction=nonstopmode  example.latex
          - lualatex                                 --interaction=nonstopmode  example.latex
          - pdftex   --shell-escape                  --interaction=nonstopmode  example.plaintex
          - xetex    --shell-escape --8bit           --interaction=nonstopmode  example.plaintex
          - luatex                                   --interaction=nonstopmode  example.plaintex
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends poppler-utils ruby
      - name: Install lt3luabridge
        run: xetex lt3luabridge.ins
      - name: Compile example document
        run: ${{ matrix.command }}
      - name: Extract text of the example document
        run: pdftotext example.pdf
      - name: Check the text of the example document
        run: grep '1+2=3' example.txt
  prerelease:
    name: Prerelease the package
    needs:
      - markdownlint
      - test
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends zip
      - name: Typeset documentation
        run: latexmk lt3luabridge.dtx
      - name: Produce lt3luabridge.zip
        run: |
          set -e
          ln -s . lt3luabridge
          zip -@ lt3luabridge < RELEASE_FILES
      - name: Upload artifact lt3luabridge.zip
        uses: actions/upload-artifact@v2
        with:
          name: lt3luabridge.zip
          path: lt3luabridge.zip
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            lt3luabridge.zip
